[package]
name = "discord_music_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "^0.1"
tracing-subscriber = "^0.3"
tracing-futures = "^0.2"
dotenv = "0.15.0"
songbird = '^0.3.2'
serde_json = "1.0.100"
serde = "1.0.189"
once_cell = "1.18.0"
rand = "0.8.5"
chrono = "0.4.31"
uuid = "1.5.0"
regex = "1.10.2"
async-trait = "0.1.74"

[dependencies.serenity]
version = "^0.11.7"
# features = ["client", "standard_framework", "voice", "rustls_backend", "utils", "builder", "chrono"]

[dependencies.tokio]
version = "^1.34"
features = ["macros", "rt-multi-thread", "signal"]

[dependencies.youtube_dl]
version = "0.9.0"
features = ["tokio"]
